/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: schema.json
export type Milestone = {
  _type: 'milestone'
  value: string
  label: string
}

export type Merchant = {
  _type: 'merchant'
  name: string
  logo: ImageWithAlt
}

export type TeamMember = {
  _type: 'teamMember'
  name: string
  role: string
}

export type EventLink = {
  _type: 'eventLink'
  label: string
  url: string
}

export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type ImageWithAlt = {
  _type: 'imageWithAlt'
  asset?: SanityImageAssetReference
  media?: unknown
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  alt: string
}

export type Post = {
  _id: string
  _type: 'post'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  publishedAt: string
  excerpt?: string
  coverImage: ImageWithAlt
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?:
          'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | ({
        _key: string
      } & ImageWithAlt)
  >
  seoDescription?: string
}

export type Slug = {
  _type: 'slug'
  current: string
  source?: string
}

export type Chapter = {
  _id: string
  _type: 'chapter'
  _createdAt: string
  _updatedAt: string
  _rev: string
  country: string
  description?: string
  images?: Array<
    {
      _key: string
    } & ImageWithAlt
  >
}

export type Event = {
  _id: string
  _type: 'event'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  date: string
  description?: string
  images?: Array<
    {
      _key: string
    } & ImageWithAlt
  >
  links?: Array<
    {
      _key: string
    } & EventLink
  >
}

export type Project = {
  _id: string
  _type: 'project'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  status: 'ongoing' | 'completed'
  image: ImageWithAlt
  description?: string
  progress?: number
  date: string
}

export type LoyaltyPage = {
  _id: string
  _type: 'loyaltyPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  merchants?: Array<
    {
      _key: string
    } & Merchant
  >
}

export type MembershipPage = {
  _id: string
  _type: 'membershipPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  poster: ImageWithAlt
  documentsRequired?: Array<string>
  payment?: {
    lifeMembership?: {
      label?: string
      badge?: string
      price?: string
    }
    replacementCard?: {
      label?: string
      price?: string
    }
  }
  ctaLabel?: string
}

export type ProjectsPage = {
  _id: string
  _type: 'projectsPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  dehiwala: {
    show?: boolean
    title: string
    body?: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }>
    image: ImageWithAlt
    highlightsLabel?: string
    highlightsUrl?: string
  }
}

export type AboutPage = {
  _id: string
  _type: 'aboutPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  president: {
    name: string
    role: string
    photo: ImageWithAlt
    message: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }>
  }
  team?: {
    year?: string
    patrons?: Array<
      {
        _key: string
      } & TeamMember
    >
    committee?: Array<
      {
        _key: string
      } & TeamMember
    >
  }
}

export type HomePage = {
  _id: string
  _type: 'homePage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  hero: {
    eyebrow?: string
    headline: string
    image: ImageWithAlt
    ctaLabel: string
    ctaUrl: string
    secondaryCtaLabel?: string
    secondaryCtaUrl?: string
  }
  milestones?: Array<
    {
      _key: string
    } & Milestone
  >
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x: number
  y: number
  height: number
  width: number
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | Milestone
  | Merchant
  | TeamMember
  | EventLink
  | SanityImageAssetReference
  | ImageWithAlt
  | Post
  | Slug
  | Chapter
  | Event
  | Project
  | LoyaltyPage
  | MembershipPage
  | ProjectsPage
  | AboutPage
  | HomePage
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
